// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD50Mx0ZFYWjfYyXOyvBDRH759mjTfORKw',
    appId: '1:778953134788:web:1abb23f374c1908ae3af91',
    messagingSenderId: '778953134788',
    projectId: 'delivery-9ef33',
    authDomain: 'delivery-9ef33.firebaseapp.com',
    storageBucket: 'delivery-9ef33.firebasestorage.app',
    measurementId: 'G-ZZGGDDTB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGxfqYetsqs4cU--8mLMoX5k-jLg--cQQ',
    appId: '1:778953134788:android:1956a0d84ac8234ae3af91',
    messagingSenderId: '778953134788',
    projectId: 'delivery-9ef33',
    storageBucket: 'delivery-9ef33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDGoppcXRYelbbIYg2ITzqawfRyLHj9c',
    appId: '1:778953134788:ios:4041f7526f5cb3b0e3af91',
    messagingSenderId: '778953134788',
    projectId: 'delivery-9ef33',
    storageBucket: 'delivery-9ef33.firebasestorage.app',
    iosBundleId: 'com.example.continuousEntregation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDGoppcXRYelbbIYg2ITzqawfRyLHj9c',
    appId: '1:778953134788:ios:4041f7526f5cb3b0e3af91',
    messagingSenderId: '778953134788',
    projectId: 'delivery-9ef33',
    storageBucket: 'delivery-9ef33.firebasestorage.app',
    iosBundleId: 'com.example.continuousEntregation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD50Mx0ZFYWjfYyXOyvBDRH759mjTfORKw',
    appId: '1:778953134788:web:f4425b9be849b016e3af91',
    messagingSenderId: '778953134788',
    projectId: 'delivery-9ef33',
    authDomain: 'delivery-9ef33.firebaseapp.com',
    storageBucket: 'delivery-9ef33.firebasestorage.app',
    measurementId: 'G-DHWQ4K6T4Y',
  );
}
